server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:9297
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

jwt:
  secret-key: Q2xhdmUgU2VjcmV0YSBwYXJhIHByb3llY3RvIEp3dCAxMjM0NTY3ODkgQWJjZA


